target_accuracy: 0.8
device: cuda
pin_memory: True
batch_size: 64
max_neighbors: 1000000
tolerance: 0.1

#Add this value to a positive number before taking
#an inverse to prevent infinity
epsilon: 1e-6

# distance raised to the inverse to the -exponent
exponent: 6

influence_cone_factor: 4
kernel_type : 'influence_cone' # euclidean


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
