data: cifar100 #mnist
target_accuracy: 0.90
device: cuda
pin_memory: True
batch_size: 64
max_neighbors: 100000
train_network: True
max_count: 3

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
