data: cifar100 #mnist
target_accuracy: 0.90
device: cuda
pin_memory: True
batch_size: 64
max_neighbors: 100000
train_network: False
max_count: 3
kernel_type: "euclidian_pyramid"
epsilon: 1e-6
exponent: -2
scales: 4
influence_cone_factor: 2

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
