target_accuracy: 0.9
device: cuda
pin_memory: True
batch_size: 64
max_neighbors: 1000000
tolerance: 0.01
num_features: 10
num_targets: 1
gutenberg_train: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
gutenberg_test: [1]

# Related to testing
train: True
text_prompt: "Who are you"
directory: null
text_prediction_length: 100

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
